Vectorized operations:
Generate $1000 \times 1000$ matrix of random integers between 0 and 19.

In [29]:
import numpy as np
import random as rand
import timeit

N = 1000
random_matrix = np.zeros((N, N))

for i in range(len(random_matrix)):
    for j in range(len(random_matrix)):
        random_matrix[i][j] = rand.randint(0,19)

print(random_matrix)

[[13.  4. 19. ... 10. 19.  1.]
 [ 4. 11.  6. ...  6.  0.  9.]
 [14. 13. 17. ...  4. 12. 13.]
 ...
 [ 1. 13. 11. ...  2. 13. 16.]
 [ 9.  4. 12. ...  5. 16. 12.]
 [11.  0.  9. ...  7.  6. 12.]]


Using the library "random", gives a tremendous speedup in performance compared to numpy.random.randint.

Compute the sum of all diagonal elements with for loop.

In [40]:
def trace_forloop(random_matrix):
    sum_diagonal = 0
    for i in range(len(random_matrix)):
        sum_diagonal += random_matrix[i][i] 
    return int(sum_diagonal)

print(trace_forloop(random_matrix))

9419


Compute the sum of all diagonal elements with NumPy linear algebra function

In [31]:
trace = np.trace(random_matrix, dtype = int)
print(trace)

9419


Comparing the for-loop and np.trace performance:
with %%timeit

In [42]:
%timeit for x in range(100): trace_forloop(random_matrix)
%timeit for x in range(100): np.trace(random_matrix)

26.8 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
392 µs ± 21.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


np.trace is clearly faster.